### PR TITLE
Default Option Values Support

### PR DESCRIPTION
**Pull request by ghost**
@benhutton This is one potential solution to address Issue #5. This is not originally what I was going to go with, but I think it provides a relatively straight forward solution that will be easy to build on and add support for #2.

Another approach would be to simply except Component developers to have their action method insert default values, but I'm guessing that is not what @desiringgod/frontend is looking for.

### CODE REVIEW

**Comment by joeosburn-desiringgod** [comment]
@scottcorgan @shanebo Check out the example implementation here: https://github.com/desiringgod/components-rails/blob/a0809bf5d90b934c1982895ac8b005329af4bff9/spec/features/rendering_spec.rb#L76

**Comment by benhutton** [comment]
@joeosburn-desiringgod how do you see required options (#2) fitting into this API?

**Review by benhutton — APPROVED** [review]

**Comment by joeosburn-desiringgod** [comment]
@benhutton 
```
option :my_option, { default: 'default value', required: true }
```

**Comment by joeosburn-desiringgod** [comment]
@benhutton Yes, but I'd still leave the api like this.

**Review by shanebo — APPROVED** [review]

**Comment by scottcorgan** [comment]
@joeosburn-desiringgod I like the API for `required`. Could you do a check and throw an error if both `default` and `required` are used?

**Comment by scottcorgan** [comment]
@joeosburn-desiringgod I'm all about throwing errors so we know exactly the mistake we made. Makes for low cognitive load 👍

**Review by scottcorgan — APPROVED** [review]

**Comment by shanebo** [comment]
@joeosburn-desiringgod @benhutton @scottcorgan 

I'm trying to think through when we'd ever have a required key that doesn't have a default value. Also if we didn't pass in a required key, wouldn't it throw anyway? If so, why bloat the component code to cover something that will already error out? Is it only to get cleaner error messages?

**Comment by scottcorgan** [comment]
@shanebo a required option would never have a default value, because it's required. An error should be thrown if that option is not given to the component. Default values are for options that are, sigh, optional.

Which, @joeosburn-desiringgod, begs the question, maybe `option` isn't the right word for these since some would be optional and some would be required. `attributes` or `properties` line up more with front-end terminology 👍

**Comment by joeosburn-desiringgod** [comment]
Closing in favor of #20

**Pull request closed without merging**
