### PR TITLE
Add BSD 3-Clause License

### PR DESCRIPTION
**Pull request by hchasey**
Add a license file to clarify usage limitations and liabilities

### CODE REVIEW

**Comment by scottcorgan** [comment]
👍 excellent. I'm not a license guru (but I like the part from BSD3 about

> Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products

I usually use MIT, that line is important for us.

**Review by benhutton — APPROVED** [review]

**Comment by hchasey** [comment]
@joeosburn-desiringgod – let me know if this is clear to be merged. Thanks!

**Review by ghost — APPROVED** [review]
If we're going to keep it public, it's prudent to have a proper license. However, my approval of this PR is not approval of keeping this public.

**Comment by hchasey** [comment]
Thanks and noted @joeosburn-desiringgod

**Pull request merged**
