### PR TITLE
Specs for block_content

### PR DESCRIPTION
**Pull request by joeosburn-desiringgod**
This will resolve issues #3 and #7.

### CODE REVIEW

**Comment by benhutton** [comment]
@joeosburn-desiringgod you're saying that #3 and #7 are not actually happening at all?

**Comment by joeosburn-desiringgod** [comment]
@benhutton Yes, the previous PR apparently fixed them.

**Comment by joeosburn-desiringgod** [comment]
@benhutton Check out the first commit

**Comment by benhutton** [comment]
@joeosburn-desiringgod that looks okay

**Comment by joeosburn-desiringgod** [comment]
@benhutton OK check out the first commit now.

**Comment by joeosburn-desiringgod** [comment]
@benhutton https://github.com/desiringgod/components-rails/pull/9/commits/88d4a4be577e4110fdbda3465cc826455d4f6a55

**Pull request merged**
